from python:2.7

WORKDIR /usr/src/app
ADD requirements.txt /usr/src/app/
RUN pip install -r requirements.txt
ADD . /usr/src/app/
RUN pip install .

ENTRYPOINT ["python", "-m", "senpy", "-f", ".", "--host", "0.0.0.0"]
