version: '3'
services:
    dev:
        image: gsiupm/senpy:latest
        entrypoint: ["/bin/bash"]
        working_dir: "/senpy-plugins"
        tty: true
        ports:
            - "127.0.0.1:5005:5000"
        volumes:
            - ".:/senpy-plugins"
    test:
        image: gsiupm/senpy:latest
        entrypoint: ["py.test"]
        working_dir: "/usr/src/app/"
        volumes:
            - ".:/senpy-plugins/"
        command:
          []
    meaningcloud:
        image: "${IMAGENAME-gsiupm/meaningcloud}:${VERSION-dev}"
        build:
          context: .
          dockerfile: Dockerfile-3.5
        ports:
            - 5001:5000
        volumes:
            - "./data:/data"
