---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: senpy-ingress
  labels:
    app: senpy-latest
spec:
  rules:
  - host: senpy-latest.gsi.upm.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: senpy-latest
            port:
              number: 5000
  - host: latest.senpy.gsi.upm.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: senpy-latest
            port:
              number: 5000
