---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: senpy-latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: senpy-latest
  template:
    metadata:
      labels:
        app: senpy-latest
        role: senpy-latest
    spec:
      containers:
      - name: senpy-latest
        image: $IMAGEWTAG
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
          - name: web
            containerPort: 5000
