version: '3'
services:
    dev:
        image: "gsiupm/senpy-taiger:${VERSION:-dev}"
        working_dir: "/senpy-plugins"
        ports:
            - "127.0.0.1:5005:5000"
        volumes:
            - ".:/senpy-plugins"
        environment:
            TAIGER_ENDPOINT: "${TAIGER_ENDPOINT:-http://somedi-taiger.hopto.org:5406/es_sentiment_analyzer_3classes}"
